# frozen_string_literal: true

require 'rails_helper'
require 'zlib'

# The Zasmate brand rasters under `public/` are generated by
# `scripts/brand/generate-icons.sh` from the JPEG masters in `docs/brand/`.
# This spec guards the OUTPUT, because the pipeline's one real failure mode is
# silent: it emits a perfectly valid PNG that happens to have the logo punched
# out of it.
#
# The masters sit on an opaque #F7F7F7 field. The obvious way to lift them off,
#
#     convert master.jpeg -fuzz 12% -transparent '#F7F7F7' mark.png
#
# matches that colour GLOBALLY, and the logo's "Z" and the speech-bubble
# interior are the same near-white — so they go transparent too. The file still
# opens, still has the right dimensions, still has an alpha channel. Every cheap
# assertion passes. Measured on the real artwork:
#
#     correct (floodfill)    13.1% of pixels near-white AND opaque
#     broken  (-transparent)  0.0%
#
# So the assertion is that number. The white Z is what disappears, so the white
# Z is what gets counted.
#
# PNG is decoded here in plain Ruby rather than through mini_magick so the spec
# does not depend on an ImageMagick binary being present on the runner.
describe 'Zasmate brand assets' do
  # Every icon slot referenced by `app/views/layouts/vueapp.html.erb` or
  # `public/manifest.json`, and the size its own filename claims. A slot that
  # changes size silently breaks the <link> tag that declares that size.
  ICON_SIZES = {
    'favicon' => [16, 32, 96, 512],
    'favicon-badge' => [16, 32, 96],
    'android-icon' => [36, 48, 72, 96, 144, 192],
    'apple-icon' => [57, 60, 72, 76, 114, 120, 144, 152, 180],
    'ms-icon' => [70, 144, 150, 310]
  }.freeze

  UNSIZED_ICONS = {
    'apple-icon.png' => 192,
    'apple-icon-precomposed.png' => 192,
    'apple-touch-icon.png' => 180,
    'apple-touch-icon-precomposed.png' => 180
  }.freeze

  # Reads IHDR and the un-filtered RGBA bytes. 8-bit RGBA, non-interlaced only,
  # which is what the generator writes and what this asserts.
  def decode(path)
    data = File.binread(path)
    expect(data[0, 8].unpack1('H*')).to eq('89504e470d0a1a0a')

    width = height = bit_depth = colour_type = interlace = nil
    idat = +''.b
    offset = 8
    while offset < data.bytesize
      length = data[offset, 4].unpack1('N')
      type = data[offset + 4, 4]
      body = data[offset + 8, length]
      case type
      when 'IHDR'
        width, height = body[0, 8].unpack('NN')
        bit_depth, colour_type = body[8, 2].unpack('CC')
        interlace = body[12].unpack1('C')
      when 'IDAT' then idat << body
      when 'IEND' then break
      end
      offset += 12 + length
    end

    expect([bit_depth, colour_type, interlace]).to eq([8, 6, 0])

    raw = Zlib::Inflate.inflate(idat)
    bpp = 4
    stride = width * bpp
    pixels = "\0".b * (height * stride)

    height.times do |y|
      filter = raw.getbyte(y * (stride + 1))
      row = y * (stride + 1) + 1
      stride.times do |x|
        cur = raw.getbyte(row + x)
        left = x >= bpp ? pixels.getbyte(y * stride + x - bpp) : 0
        up = y.positive? ? pixels.getbyte((y - 1) * stride + x) : 0
        up_left = x >= bpp && y.positive? ? pixels.getbyte((y - 1) * stride + x - bpp) : 0
        value =
          case filter
          when 0 then cur
          when 1 then cur + left
          when 2 then cur + up
          when 3 then cur + ((left + up) / 2)
          when 4 then cur + paeth(left, up, up_left)
          else raise "#{path}: unknown PNG filter #{filter} on row #{y}"
          end
        pixels.setbyte(y * stride + x, value & 0xff)
      end
    end

    { width: width, height: height, pixels: pixels }
  end

  def paeth(left, up, up_left)
    p = left + up - up_left
    dl = (p - left).abs
    du = (p - up).abs
    dul = (p - up_left).abs
    return left if dl <= du && dl <= dul
    return up if du <= dul

    up_left
  end

  # Fraction of pixels that are fully opaque AND near-white — i.e. the logo's Z.
  def white_and_opaque_fraction(png)
    hits = 0
    (png[:width] * png[:height]).times do |i|
      base = i * 4
      next unless png[:pixels].getbyte(base + 3) > 250

      hits += 1 if png[:pixels].getbyte(base) > 230 &&
                   png[:pixels].getbyte(base + 1) > 230 &&
                   png[:pixels].getbyte(base + 2) > 230
    end
    hits.to_f / (png[:width] * png[:height])
  end

  def every_icon
    ICON_SIZES.flat_map { |stem, sizes| sizes.map { |s| ["public/#{stem}-#{s}x#{s}.png", s] } } +
      UNSIZED_ICONS.map { |name, size| ["public/#{name}", size] }
  end

  it 'emits every icon slot the layout and manifest reference' do
    missing = every_icon.reject { |(path, _)| Rails.root.join(path).exist? }
    expect(missing).to be_empty, "missing (run scripts/brand/generate-icons.sh): #{missing.map(&:first)}"
  end

  it 'keeps every icon at the size its own filename claims' do
    wrong = every_icon.filter_map do |(path, size)|
      png = decode(Rails.root.join(path))
      "#{path} is #{png[:width]}x#{png[:height]}, not #{size}x#{size}" unless png[:width] == size && png[:height] == size
    end
    expect(wrong).to be_empty, wrong.join("\n")
  end

  # The regression this file exists for. A global opacity check would NOT catch
  # it cleanly — the broken build is still ~26% opaque from the cyan bubble.
  it 'still has the white Z in every plain icon at or above 32px' do
    # Below 32px the Z is only a few pixels wide and antialiasing pulls it off
    # pure white, so the count stops being a reliable signal at those sizes.
    paths = ICON_SIZES.except('favicon-badge').flat_map do |stem, sizes|
      sizes.select { |s| s >= 32 }.map { |s| "public/#{stem}-#{s}x#{s}.png" }
    end

    # The floor is 0.05, not something snug under the real numbers. What it has
    # to separate from is ZERO — the broken recipe removes the Z entirely — so
    # width here is free, while tightness is not: the smallest icon in this set
    # measures 0.0801 (32x32, where antialiasing pulls much of the thin Z off
    # pure white), and a floor of 0.08 would sit close enough to flake on a
    # re-render that changed nothing anyone cares about.
    thin = paths.filter_map do |path|
      fraction = white_and_opaque_fraction(decode(Rails.root.join(path)))
      "#{path}: #{(fraction * 100).round(2)}% white-and-opaque" if fraction < 0.05
    end
    expect(thin).to be_empty,
                    "the logo's white Z is missing or thin — the -transparent recipe is back?\n#{thin.join("\n")}"
  end

  it 'points the configured brand assets at files that exist and carry artwork' do
    %w[logo.svg logo_dark.svg logo_thumbnail.svg].each do |name|
      path = Rails.root.join('public/brand-assets', name)
      expect(path).to exist
      # The artwork is raster inside an SVG wrapper; the extension is a contract
      # with config/installation_config.yml, the payload is a base64 PNG.
      expect(path.read).to include('data:image/png;base64,')
    end
  end

  it 'has no Chatwoot branding left in the installation defaults' do
    config = YAML.load_file(Rails.root.join('config/installation_config.yml'))
    branding = config.select { |row| %w[INSTALLATION_NAME BRAND_NAME BRAND_URL WIDGET_BRAND_URL].include?(row['name']) }

    expect(branding.length).to eq(4)
    branding.each do |row|
      expect(row['value'].to_s.downcase).not_to include('chatwoot'), "#{row['name']} is still #{row['value']}"
    end
  end
end
