# frozen_string_literal: true

require 'rails_helper'
require 'zlib'

# The Zasmate brand rasters under `public/` are generated by
# `scripts/brand/generate-icons.sh` from the PNG masters in `docs/brand/`.
# This spec guards the OUTPUT, because the pipeline's failure modes are silent:
# the file opens, has the right size and an alpha channel, and still is not the
# logo.
#
# Since 2026-09-28 the masters are the orange "Z" + sparkle and the orange
# wordmark on a TRANSPARENT background. What can go wrong now is the opposite of
# the old JPEG era (when a global `-transparent` punched the white Z out):
# an icon built from a flattened or JPEG export comes out on an opaque square,
# or a bad crop leaves a mostly-empty canvas. So the spec counts the two things
# that separate the real artwork from both: opaque ORANGE pixels, and genuinely
# transparent corners.
#
# PNG is decoded here in plain Ruby rather than through mini_magick so the spec
# does not depend on an ImageMagick binary being present on the runner.
describe 'Zasmate brand assets' do
  # Every icon slot referenced by `app/views/layouts/vueapp.html.erb` or
  # `public/manifest.json`, and the size its own filename claims. A slot that
  # changes size silently breaks the <link> tag that declares that size.
  ICON_SIZES = {
    'favicon' => [16, 32, 96, 512],
    'favicon-badge' => [16, 32, 96],
    'android-icon' => [36, 48, 72, 96, 144, 192],
    'apple-icon' => [57, 60, 72, 76, 114, 120, 144, 152, 180],
    'ms-icon' => [70, 144, 150, 310]
  }.freeze

  UNSIZED_ICONS = {
    'apple-icon.png' => 192,
    'apple-icon-precomposed.png' => 192,
    'apple-touch-icon.png' => 180,
    'apple-touch-icon-precomposed.png' => 180
  }.freeze

  # Reads IHDR and the un-filtered RGBA bytes. 8-bit RGBA, non-interlaced only,
  # which is what the generator writes and what this asserts.
  def decode(path)
    data = File.binread(path)
    expect(data[0, 8].unpack1('H*')).to eq('89504e470d0a1a0a')

    width = height = bit_depth = colour_type = interlace = nil
    idat = +''.b
    offset = 8
    while offset < data.bytesize
      length = data[offset, 4].unpack1('N')
      type = data[offset + 4, 4]
      body = data[offset + 8, length]
      case type
      when 'IHDR'
        width, height = body[0, 8].unpack('NN')
        bit_depth, colour_type = body[8, 2].unpack('CC')
        interlace = body[12].unpack1('C')
      when 'IDAT' then idat << body
      when 'IEND' then break
      end
      offset += 12 + length
    end

    expect([bit_depth, colour_type, interlace]).to eq([8, 6, 0])

    raw = Zlib::Inflate.inflate(idat)
    bpp = 4
    stride = width * bpp
    pixels = "\0".b * (height * stride)

    height.times do |y|
      filter = raw.getbyte(y * (stride + 1))
      row = y * (stride + 1) + 1
      stride.times do |x|
        cur = raw.getbyte(row + x)
        left = x >= bpp ? pixels.getbyte(y * stride + x - bpp) : 0
        up = y.positive? ? pixels.getbyte((y - 1) * stride + x) : 0
        up_left = x >= bpp && y.positive? ? pixels.getbyte((y - 1) * stride + x - bpp) : 0
        value =
          case filter
          when 0 then cur
          when 1 then cur + left
          when 2 then cur + up
          when 3 then cur + ((left + up) / 2)
          when 4 then cur + paeth(left, up, up_left)
          else raise "#{path}: unknown PNG filter #{filter} on row #{y}"
          end
        pixels.setbyte(y * stride + x, value & 0xff)
      end
    end

    { width: width, height: height, pixels: pixels }
  end

  def paeth(left, up, up_left)
    p = left + up - up_left
    dl = (p - left).abs
    du = (p - up).abs
    dul = (p - up_left).abs
    return left if dl <= du && dl <= dul
    return up if du <= dul

    up_left
  end

  # Fraction of pixels that are fully opaque AND in the brand's orange range
  # (#F5930D → #E8640A and the artwork's shading around it).
  def orange_and_opaque_fraction(png)
    hits = 0
    (png[:width] * png[:height]).times do |i|
      base = i * 4
      next unless png[:pixels].getbyte(base + 3) > 250

      r = png[:pixels].getbyte(base)
      g = png[:pixels].getbyte(base + 1)
      b = png[:pixels].getbyte(base + 2)
      hits += 1 if r > 200 && g > 60 && g < 200 && b < 100
    end
    hits.to_f / (png[:width] * png[:height])
  end

  def corner_alphas(png)
    w = png[:width]
    h = png[:height]
    [[0, 0], [w - 1, 0], [0, h - 1], [w - 1, h - 1]].map do |(x, y)|
      png[:pixels].getbyte(((y * w) + x) * 4 + 3)
    end
  end

  def every_icon
    ICON_SIZES.flat_map { |stem, sizes| sizes.map { |s| ["public/#{stem}-#{s}x#{s}.png", s] } } +
      UNSIZED_ICONS.map { |name, size| ["public/#{name}", size] }
  end

  it 'emits every icon slot the layout and manifest reference' do
    missing = every_icon.reject { |(path, _)| Rails.root.join(path).exist? }
    expect(missing).to be_empty, "missing (run scripts/brand/generate-icons.sh): #{missing.map(&:first)}"
  end

  it 'keeps every icon at the size its own filename claims' do
    wrong = every_icon.filter_map do |(path, size)|
      png = decode(Rails.root.join(path))
      "#{path} is #{png[:width]}x#{png[:height]}, not #{size}x#{size}" unless png[:width] == size && png[:height] == size
    end
    expect(wrong).to be_empty, wrong.join("\n")
  end

  # Plain icons only: the badge set adds a red dot in one corner by design.
  def plain_icons(min_size: 0)
    ICON_SIZES.except('favicon-badge').flat_map do |stem, sizes|
      sizes.select { |s| s >= min_size }.map { |s| "public/#{stem}-#{s}x#{s}.png" }
    end
  end

  it 'draws the orange artwork in every plain icon at or above 32px' do
    # Measured on the 2026-09-28 artwork: 0.1465 at 32x32 (antialiasing pulls
    # the small sizes off full opacity) up to 0.2608 at 512x512. What the floor
    # has to separate from is an icon with no orange artwork in it at all, so
    # it sits well under the smallest real value rather than snug against it.
    # Below 32px antialiasing makes the count unreliable.
    thin = plain_icons(min_size: 32).filter_map do |path|
      fraction = orange_and_opaque_fraction(decode(Rails.root.join(path)))
      "#{path}: #{(fraction * 100).round(2)}% orange-and-opaque" if fraction < 0.10
    end
    expect(thin).to be_empty, "the orange mark is missing or thin:\n#{thin.join("\n")}"
  end

  it 'keeps every plain icon on a transparent background' do
    # An icon generated from a flattened or JPEG export sits on an opaque square;
    # its corners are the tell. The mark is padded 8% inside its square, so no
    # artwork reaches a corner.
    opaque = plain_icons.filter_map do |path|
      alphas = corner_alphas(decode(Rails.root.join(path)))
      "#{path}: corner alphas #{alphas.inspect}" unless alphas.all?(&:zero?)
    end
    expect(opaque).to be_empty, "icons with an opaque background:\n#{opaque.join("\n")}"
  end

  it 'points the configured brand assets at files that exist and carry artwork' do
    %w[logo.svg logo_dark.svg logo_thumbnail.svg].each do |name|
      path = Rails.root.join('public/brand-assets', name)
      expect(path).to exist
      # The artwork is raster inside an SVG wrapper; the extension is a contract
      # with config/installation_config.yml, the payload is a base64 PNG.
      expect(path.read).to include('data:image/png;base64,')
    end
  end

  it 'has no Chatwoot branding left in the installation defaults' do
    config = YAML.load_file(Rails.root.join('config/installation_config.yml'))
    branding = config.select { |row| %w[INSTALLATION_NAME BRAND_NAME BRAND_URL WIDGET_BRAND_URL].include?(row['name']) }

    expect(branding.length).to eq(4)
    branding.each do |row|
      expect(row['value'].to_s.downcase).not_to include('chatwoot'), "#{row['name']} is still #{row['value']}"
    end
  end
end
